#!/bin/bash

set -e

source "../../.env.android"

INSTALL_DIR=build/android/build

rm -rf ${INSTALL_DIR}

qmake -config release "CONFIG += release_android"

make clean
make -j8
make install INSTALL_ROOT=${INSTALL_DIR}

androiddeployqt --gradle --no-gdbserver --output ${INSTALL_DIR} --input android-libskypuff.so-deployment-settings.json --android-platform android-29

mv ${INSTALL_DIR}/build/outputs/apk/debug/build-debug.apk skypuff-andoird.apk
